/* COMPLETE WORD DATABASE (1000+ Words) */

window.wordDatabase = {
    // --- AESTHETIC / SOFT ---
    aesthetic: [
        "Velvet", "Lunar", "Honey", "Silk", "Ethereal", "Bloom", "Mist", "Cloud", "Vanilla", "Rose",
        "Divine", "Hollow", "Pure", "Fairy", "Angel", "Ghost", "Pearl", "Crystal", "Golden", "Quiet",
        "Secret", "Lost", "Dreamy", "Lush", "Nova", "Stellar", "Cosmic", "Petal", "Aura", "Glow",
        "Azure", "Ivory", "Opal", "Quartz", "Ruby", "Sapphire", "Emerald", "Jade", "Amber", "Coral",
        "Hazel", "Iris", "Lilac", "Violet", "Indigo", "Teal", "Cyan", "Aqua", "Ocean", "River",
        "Rain", "Snow", "Wind", "Breeze", "Storm", "Thunder", "Lightning", "Sky", "Star", "Moon",
        "Sun", "Sol", "Luna", "Astra", "Cosmos", "Galaxy", "Nebula", "Comet", "Meteor", "Eclipse",
        "Horizon", "Dawn", "Dusk", "Twilight", "Midnight", "Noon", "Morning", "Evening", "Night", "Day",
        "Light", "Dark", "Shadow", "Shade", "Glimmer", "Shimmer", "Sparkle", "Glitter", "Shine", "Bright",
        "Soft", "Gentle", "Kind", "Warm", "Cold", "Cool", "Fresh", "Clean", "Clear", "Lucid",
        "Vivid", "Pale", "Faint", "Dim", "Dull", "Grey", "Black", "White", "Silver", "Gold",
        "Bronze", "Copper", "Platinum", "Titanium", "Chrome", "Metal", "Glass", "Mirror", "Reflection", "Echo",
        "Sound", "Silence", "Whisper", "Voice", "Song", "Music", "Melody", "Rhythm", "Beat", "Pulse",
        "Heart", "Soul", "Spirit", "Mind", "Body", "Life", "Death", "Love", "Hate", "Hope",
        "Dream", "Wish", "Desire", "Passion", "Fire", "Flame", "Ash", "Dust", "Smoke", "Fog",
        "Haze", "Blur", "Focus", "Vision", "Sight", "View", "Scene", "Image", "Picture", "Photo",
        "Film", "Movie", "Story", "Tale", "Myth", "Legend", "Fable", "Lore", "Saga", "Epic",
        "Poem", "Verse", "Rhyme", "Lyric", "Word", "Name", "Title", "Label", "Tag", "Mark",
        "Sign", "Symbol", "Icon", "Logo", "Badge", "Crest", "Emblem", "Token", "Charm", "Amulet",
        "Talisman", "Relic", "Artifact", "Item", "Object", "Thing", "Stuff", "Matter", "Energy", "Power",
        "Force", "Strength", "Might", "Vigor", "Vitality", "Health", "Wellness", "Fitness", "Balance", "Harmony",
        "Peace", "Calm", "Zen", "Serene", "Tranquil", "Still", "Quiet", "Silent", "Mute", "Numb",
        "Void", "Empty", "Blank", "Null", "Zero", "One", "Two", "Three", "Four", "Five",
        "Six", "Seven", "Eight", "Nine", "Ten", "First", "Last", "Start", "End", "Begin",
        "Finish", "Stop", "Go", "Run", "Walk", "Fly", "Swim", "Jump", "Hop", "Skip",
        "Dance", "Sing", "Play", "Game", "Sport", "Match", "Race", "Fight", "Battle", "War",
        "Win", "Lose", "Draw", "Tie", "Score", "Point", "Level", "Stage", "Phase", "Step",
        "Round", "Turn", "Move", "Action", "React", "Respond", "Reply", "Ask", "Say", "Tell",
        "Talk", "Speak", "Chat", "Text", "Write", "Read", "Learn", "Know", "Think", "Feel",
        "See", "Hear", "Smell", "Taste", "Touch", "Sense", "Detect", "Find", "Seek", "Search",
        "Look", "Watch", "View", "Observe", "Notice", "Spot", "Spy", "Scan", "Scope", "Track",
        "Trace", "Follow", "Chase", "Hunt", "Catch", "Capture", "Trapped", "Free", "Wild", "Tame",
        "Pet", "Animal", "Beast", "Creature", "Monster", "Alien", "Robot", "Cyborg", "Android", "Human"
    ],

    // --- GAMER / COOL ---
    gamer: [
        "Toxic", "Rapid", "Shadow", "Elite", "Pro", "Hyper", "Cyber", "Neon", "Rogue", "Savage",
        "Viper", "Ghost", "Sniper", "Dark", "Venom", "Iron", "Steel", "Alpha", "Omega", "Chaos",
        "Storm", "Void", "Pixel", "Glitch", "Turbo", "Sonic", "Fatal", "Reaper", "Strike", "Nitro",
        "Abyss", "Acid", "Aggro", "Aim", "Ammo", "Arcane", "Armor", "Arrow", "Assassin", "Assault",
        "Attack", "Axe", "Bane", "Barbarian", "Baron", "Base", "Bash", "Battle", "Beast", "Berserk",
        "Blade", "Blast", "Blaze", "Blitz", "Blood", "Bolt", "Bomb", "Boss", "Brawl", "Breach",
        "Break", "Bullet", "Burn", "Burst", "Cannon", "Captain", "Carnage", "Castle", "Chief", "Clash",
        "Claw", "Club", "Cobra", "Code", "Combat", "Command", "Control", "Core", "Crash", "Crazy",
        "Creep", "Crimson", "Crit", "Crow", "Cruel", "Crush", "Cryo", "Crypt", "Curse", "Cut",
        "Cycle", "Dagger", "Damage", "Danger", "Dare", "Dash", "Dead", "Death", "Decay", "Deep",
        "Defeat", "Defense", "Demon", "Destroy", "Devil", "Die", "Dirt", "Disaster", "Divine", "Dominate",
        "Doom", "Dragon", "Dread", "Drive", "Drop", "Drone", "Drug", "Duke", "Dungeon", "Dust",
        "Dynamite", "Eagle", "Edge", "Electro", "Element", "Ember", "Enemy", "Energy", "Engine", "Enigma",
        "Epic", "Escape", "Evil", "Execute", "Exile", "Explode", "Extreme", "Eye", "Fade", "Falcon",
        "Full", "Fury", "Fuse", "Future", "Gank", "Gas", "Gate", "Gear", "General", "Genius",
        "Giant", "Glory", "Gnome", "Goblin", "God", "Gold", "Golem", "Gore", "Grand", "Grave",
        "Gravity", "Great", "Green", "Grenade", "Grey", "Grid", "Grim", "Grind", "Grip", "Grizzly",
        "Ground", "Guard", "Guild", "Gun", "Guru", "Hack", "Hail", "Halo", "Hammer", "Hand",
        "Hard", "Harm", "Hawk", "Hazard", "Head", "Heat", "Heavy", "Hell", "Hero", "Hex",
        "High", "Hit", "Hive", "Hollow", "Holy", "Honor", "Hook", "Hope", "Horde", "Horror",
        "Host", "Hot", "Hound", "Huge", "Human", "Hunt", "Hunter", "Hurt", "Hydro", "Hype",
        "Ice", "Icon", "Ignite", "Illusion", "Immortal", "Impact", "Impulse", "Inferno", "Infinite", "Ink",
        "Insane", "Insect", "Inside", "Instant", "Intel", "Iron", "Island", "Jack", "Jade", "Jaguar",
        "Jail", "Jet", "Jinx", "Joker", "Judge", "Juice", "Jungle", "Junk", "Just", "Justice",
        "Karma", "Katana", "Keep", "Key", "Kick", "Kid", "Kill", "Killer", "King", "Kingdom",
        "Kiss", "Knight", "Knock", "Knot", "Kraken", "Krypton", "KungFu", "Lab", "Lace", "Lag",
        "Lair", "Lake", "Lamp", "Lance", "Land", "Lane", "Laser", "Last", "Late", "Lava",
        "Law", "Lead", "Leader", "Leaf", "League", "Leak", "Legend", "Legion", "Lemon", "Lens",
        "Leo", "Level", "Liar", "Life", "Lift", "Light", "Lightning", "Lilac", "Limit", "Line",
        "Link", "Lion", "Liquid", "List", "Lit", "Live", "Load", "Lobster", "Lock", "Loco"
    ],

    // --- CUTE / KAWAII ---
    cute: [
        "Smol", "Tiny", "Puff", "Mochi", "Boba", "Peach", "Bunny", "Kitty", "Puppy", "Sugar",
        "Candy", "Cookie", "Berry", "Daisy", "Fluffy", "Jelly", "Minty", "Star", "Heart", "Love",
        "Baby", "Cinnamon", "Cherry", "Lemon", "Melon", "Cocoa", "Milk", "Tea", "Sunny", "Happy",
        "Angel", "Apple", "Apricot", "Balloon", "Banana", "Bear", "Bee", "Biscuit", "Bloom", "Blossom",
        "Blueberry", "Bonbon", "Bow", "Breeze", "Brownie", "Bubble", "Bud", "Bug", "Butter", "Button",
        "Cake", "Caramel", "Cat", "Charm", "Cheeky", "Cheese", "Chick", "Choco", "Cloud", "Clover",
        "Coconut", "Coffee", "Coin", "Cotton", "Cream", "Cub", "Cuddle", "Cupcake", "Cute", "Darling",
        "Deer", "Dew", "Diamond", "Dine", "Dino", "Doll", "Dolly", "Donut", "Dove", "Dream",
        "Duck", "Dumpling", "Dust", "Egg", "Elf", "Fairy", "Fawn", "Feather", "Fern", "Fig",
        "Fish", "Fizz", "Flower", "Foam", "Forest", "Fox", "Frog", "Fruit", "Fudge", "Fun",
        "Funny", "Fuzzy", "Garden", "Gem", "Giggle", "Ginger", "Glitter", "Glow", "Gold", "Goose",
        "Grape", "Grass", "Gum", "Gumdrop", "Hamster", "Hare", "Hazel", "Honey", "Hug", "Ice",
        "Icy", "Ink", "Iris", "Ivy", "Jam", "Jar", "Joy", "Juice", "Kid", "Kiss",
        "Kitten", "Kiwi", "Koala", "Lady", "Lamb", "Leaf", "Light", "Lily", "Lime", "Lion",
        "Lolly", "Lotus", "Love", "Lucky", "Lullaby", "Magic", "Mango", "Maple", "Marshmallow", "Meadow",
        "Melody", "Meow", "Mermaid", "Mew", "Mickey", "Minnie", "Mint", "Miss", "Mist", "Moon",
        "Morning", "Mouse", "Muffin", "Mushroom", "Music", "Nature", "Nest", "Night", "Noodle", "Note",
        "Nut", "Olive", "Orange", "Owl", "Panda", "Party", "Pastel", "Paw", "Pea", "Peace",
        "Peanut", "Pear", "Pearl", "Penguin", "Peony", "Pet", "Petal", "Pie", "Pig", "Piggy",
        "Pink", "Pixel", "Pixie", "Plant", "Plum", "Plush", "Poem", "Pony", "Pop", "Poppy",
        "Potion", "Pretty", "Prince", "Princess", "Pudding", "Pumpkin", "Pup", "Pure", "Purple", "Queen",
        "Rabbit", "Rain", "Rainbow", "Rare", "Raspberry", "Rat", "Ray", "Red", "Ribbon", "Rice",
        "Ring", "Robin", "Robot", "Rock", "Rocket", "Rose", "Ruby", "Sage", "Sakura", "Sand",
        "Sapphire", "Seed", "Sheep", "Shell", "Shine", "Shoe", "Silk", "Silver", "Sky", "Sleep",
        "Smile", "Snail", "Snake", "Snow", "Soda", "Soft", "Song", "Soul", "Spark", "Sparkle"
    ],

    // --- PREMIUM / SHORT ---
    premium: [
        "Lux", "Vantage", "Prisma", "Apex", "Zenith", "Flux", "Core", "Arc", "Bolt", "Echo",
        "Vista", "Prime", "Solo", "Mono", "Duo", "Trio", "Quark", "Atom", "Ion", "Cell",
        "Ace", "Act", "Add", "Age", "Aim", "Air", "All", "Alt", "Amp", "And",
        "Ant", "Any", "Ape", "App", "Ark", "Arm", "Art", "Ash", "Ask", "Bad",
        "Bag", "Ban", "Bar", "Bat", "Bay", "Bed", "Bee", "Bet", "Bib", "Bid",
        "Big", "Bin", "Bit", "Boa", "Bob", "Bog", "Box", "Boy", "Bra", "Bug",
        "Bun", "Bus", "But", "Buy", "Bye", "Cab", "Cam", "Can", "Cap", "Car",
        "Cat", "Cob", "Cod", "Cog", "Con", "Cop", "Cot", "Cow", "Cry", "Cub",
        "Cue", "Cup", "Cut", "Dad", "Dam", "Day", "Den", "Dew", "Did", "Dig",
        "Dim", "Din", "Dip", "Dog", "Dot", "Dry", "Dub", "Dud", "Due", "Dug",
        "Dun", "Dye", "Ear", "Eat", "Ebb", "Eel", "Egg", "Ego", "Elk", "Elm",
        "Emu", "End", "Era", "Eve", "Eye", "Fan", "Far", "Fat", "Fax", "Fed",
        "Fee", "Fen", "Few", "Fez", "Fib", "Fig", "Fin", "Fit", "Fix", "Flu",
        "Fly", "Fob", "Foe", "Fog", "For", "Fox", "Fry", "Fun", "Fur", "Gab",
        "Gad", "Gag", "Gal", "Gap", "Gas", "Gel", "Gem", "Get", "Gig", "Gin",
        "Git", "God", "Goo", "Got", "Gum", "Gun", "Gut", "Guy", "Gym", "Had",
        "Hag", "Ham", "Has", "Hat", "Hay", "Hem", "Hen", "Her", "Hew", "Hex",
        "Hey", "Hid", "Him", "Hip", "His", "Hit", "Hob", "Hod", "Hoe", "Hog",
        "Hop", "Hot", "How", "Hub", "Hue", "Hug", "Hum", "Hut", "Ice", "Icy",
        "Ill", "Imp", "Ink", "Inn", "Ion", "Ire", "Ivy", "Jab", "Jag", "Jam",
        "Jar", "Jaw", "Jay", "Jet", "Jig", "Job", "Jog", "Joy", "Jug", "Jut",
        "Keg", "Ken", "Key", "Kid", "Kin", "Kip", "Kit", "Lab", "Lad", "Lag",
        "Lap", "Law", "Lax", "Lay", "Led", "Lee", "Leg", "Let", "Lid", "Lie",
        "Lip", "Lit", "Lob", "Log", "Loo", "Lop", "Lot", "Low", "Lug", "Lux",
        "Lyre", "Mad", "Man", "Map", "Mar", "Mat", "Maw", "Max", "May", "Men",
        "Met", "Mew", "Mid", "Mix", "Mob", "Mod", "Mom", "Moo", "Mop", "Mow",
        "Mud", "Mug", "Mum", "Nab", "Nag", "Nan", "Nap", "Nay", "Net", "New",
        "Nil", "Nip", "Nit", "Nix", "Nod", "Non", "Nor", "Not", "Now", "Nun",
        "Nut", "Oak", "Oar", "Oat", "Odd", "Ode", "Off", "Oil", "Old", "One",
        "Opt", "Orb", "Ore", "Our", "Out", "Owe", "Owl", "Own", "Pad", "Pal"
    ],
    
    // --- NOUNS ---
    nouns: [
        "Soul", "Mind", "Vibe", "Wraith", "Phantom", "Spirit", "Legend", "Master", "King", "Lord",
        "Walker", "Runner", "Hunter", "Slayer", "Seeker", "Keeper", "Watcher", "Gazer", "Dreamer",
        "Pilot", "Rider", "Driver", "Gamer", "Player", "User", "Bot", "System", "Data", "Base", "File",
        "Admin", "Agent", "Alien", "Ally", "Angel", "Animal", "Answer", "Ant", "Apple", "Area",
        "Arm", "Army", "Art", "Atom", "Baby", "Back", "Ball", "Band", "Bank", "Bar",
        "Base", "Bat", "Bear", "Beat", "Bed", "Bee", "Beer", "Bell", "Belt", "Bird",
        "Bit", "Block", "Blood", "Blow", "Blue", "Board", "Boat", "Body", "Bomb", "Bone",
        "Book", "Boot", "Boss", "Box", "Boy", "Brain", "Bread", "Break", "Brick", "Bridge",
        "Brother", "Brush", "Bubble", "Bug", "Build", "Burn", "Bus", "Bush", "Cake", "Call",
        "Camp", "Can", "Cap", "Car", "Card", "Care", "Case", "Cash", "Cat", "Catch",
        "Cause", "Cell", "Chain", "Chair", "Chance", "Change", "Check", "Chest", "Chief", "Child",
        "Chip", "Choice", "City", "Claim", "Class", "Clock", "Cloud", "Club", "Coach", "Coal",
        "Coat", "Code", "Cold", "Color", "Comb", "Come", "Cook", "Cool", "Copy", "Cord",
        "Core", "Corn", "Cost", "Count", "Cover", "Cow", "Crack", "Crash", "Cream", "Credit",
        "Crew", "Cross", "Crowd", "Crown", "Cry", "Cup", "Curve", "Cut", "Cycle", "Dad",
        "Dance", "Date", "Day", "Deal", "Death", "Debt", "Deck", "Deep", "Deer", "Desk",
        "Devil", "Diet", "Dig", "Dirt", "Dish", "Disk", "Dog", "Door", "Dot", "Draft",
        "Drag", "Drama", "Draw", "Dream", "Dress", "Drink", "Drive", "Drop", "Drug", "Drum",
        "Duck", "Dust", "Duty", "Ear", "Earth", "East", "Edge", "Edit", "Egg", "End",
        "Energy", "Engine", "Entry", "Error", "Event", "Exit", "Eye", "Face", "Fact", "Fall",
        "Fan", "Farm", "Fat", "Father", "Fear", "Feed", "Feel", "Feet", "Field", "Fight",
        "Figure", "File", "Film", "Final", "Fire", "Fish", "Fix", "Flag", "Flame", "Flat",
        "Flight", "Floor", "Flow", "Flower", "Fly", "Focus", "Fold", "Food", "Foot", "Force",
        "Form", "Frame", "Free", "Friend", "Front", "Fruit", "Fuel", "Fun", "Fund", "Future",
        "Gain", "Game", "Gap", "Garden", "Gas", "Gate", "Gear", "Gene", "Gift", "Girl",
        "Give", "Glass", "Glove", "Goal", "God", "Gold", "Golf", "Good", "Grab", "Grade",
        "Grand", "Grant", "Grass", "Green", "Ground", "Group", "Growth", "Guard", "Guess", "Guest",
        "Guide", "Guitar", "Gun", "Guy", "Habit", "Hair", "Half", "Hall", "Hand", "Hang",
        "Hat", "Hate", "Head", "Health", "Hear", "Heart", "Heat", "Heavy", "Hell", "Help",
        "Hero", "High", "Hire", "History", "Hit", "Hold", "Hole", "Holiday", "Home", "Honey",
        "Hook", "Hope", "Horn", "Horse", "Host", "Hotel", "Hour", "House", "Human", "Hunt",
        "Hurt", "Ice", "Idea", "Image", "Impact", "Income", "Index", "Iron", "Issue", "Item",
        "Job", "Join", "Joke", "Judge", "Juice", "Jump", "Junk", "Keep", "Key", "Kick",
        "Kid", "Kill", "Kind", "King", "Kiss", "Knee", "Knife", "Knot", "Know", "Lab"
    ]
};
